### ISSUE TITLE
no matches for kind "StatefulSet" 

### ISSUE THREAD

**Issue by wajahatlateef** [ListnPlay/charts#4]
while installing helm on azure facing the below issue.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
Please help

**Comment by ryanjclark** [comment]
bump

**Comment by rjanovski** [comment]
looks like this is a [larger issue](https://github.com/helm/helm/issues/7219) with helm that is unrelated to this repo.
it happens mostly when upgrading k8s 1.15 --> 1.16 with existing apps/v1beta apiVersion.

TLDR: unfortunately the only solution is to delete and reinstall the app (or try `helm upgrade --force` if you're using helm 2)

our latest versions of druid and presto already use `apps/v1`

**Comment by mikebevz** [comment]
Guys, we see this problem, however, the chart is not installed yet. 

It's on EKS, 1.21. 

Any ideas?

**Comment by mikebevz** [comment]
We've found a solution:  we've upgraded dependencies (postgres and zookeeper) and it worked out.

```
dependencies:
- name: zookeeper
  version: 7.4.9
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 10.12.7
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled

```
